In [3]:
# we can write any and every bit of normal Python right here
a = 3
b = 7
print(b/a) # NB no need for print statement
b+a
b-a
b*a # careful: only the last line will result in any outout. NB uses __repr__ (not __str__)

2.3333333333333335


21

In [8]:
def fn(n):
    return n*n

fn(3)

9

In [9]:
# ctrl-enter will run the current cell
# shift-enter will run the current cell and insert a new cell below

In [12]:
import numpy as np # by convention call it np

In [22]:
n = np.arange(3, 10) # start, stop-before, step
# an array-range can only contain the SAME data type members
# arange is a mutable indexed collection of ONE data type
n # arange is a new data type provided by numpy
n.dtype
n

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
# n-dimensional arrays: mutable arrays of a single data type
# we can work with arrays of as many dimensions as we like. Typically 2-dimensions
d = np.random.randn(9,3) # rows, columns
d.shape # (9, 3)
d.dtype # numpy adds new data types: float64, int32 ....

dtype('float64')

In [25]:
z = np.zeros( (3,6) ) # these are floating-point zeros
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
e = np.empty( (6,3) )
e # it is not necessarily empty - it points to avaialbe 'empty' memory

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
s= d.astype(np.string_) # this is numpy syntax
print(d)
s # converting to string showed the FULL accuracy of the original floating point numbers

[[ 2.20126109  0.44195166 -0.00451976]
 [ 0.79531589  1.32796835  1.25606214]
 [-1.09608314 -0.43987394 -0.33806797]
 [ 0.18072144 -0.47111407 -0.02246793]
 [ 0.5905249   0.7539979  -0.18475486]
 [ 0.48072345 -2.50418114  0.561691  ]
 [-0.43520647 -0.18685796 -1.67242629]
 [ 1.99176235 -0.70072609  0.34900594]
 [ 0.41758262 -1.3127504   0.89682632]]


array([[b'2.2012610939291917', b'0.44195165589635943',
        b'-0.004519758171854448'],
       [b'0.7953158889230688', b'1.3279683472275317',
        b'1.2560621369130598'],
       [b'-1.0960831356954608', b'-0.43987393959278454',
        b'-0.3380679658389464'],
       [b'0.1807214384877849', b'-0.47111406684315216',
        b'-0.022467930403329946'],
       [b'0.5905249044647811', b'0.7539979020568215',
        b'-0.18475485586029028'],
       [b'0.48072345218014556', b'-2.5041811440126143',
        b'0.5616910032970832'],
       [b'-0.43520646894989473', b'-0.18685795663790988',
        b'-1.6724262889190102'],
       [b'1.9917623494087315', b'-0.7007260869952108',
        b'0.34900593808818364'],
       [b'0.41758262302297167', b'-1.3127503961533877',
        b'0.8968263188162725']], dtype='|S32')

In [36]:
# we can have as many dimensions as we like
z = np.zeros( (3,3,3) )
r = z+3 # careful - the maths does not mutate the orignal
r = r**2 # maths orperators will apply to every member of the array
r

array([[[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]],

       [[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]],

       [[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]]])

In [39]:
# we can grab members from the array using indexing
d[1:4:2] # start:stop-before:step

array([[ 0.79531589,  1.32796835,  1.25606214],
       [ 0.18072144, -0.47111407, -0.02246793]])

In [41]:
d.T # T will transpose an array

array([[ 2.20126109,  0.79531589, -1.09608314,  0.18072144,  0.5905249 ,
         0.48072345, -0.43520647,  1.99176235,  0.41758262],
       [ 0.44195166,  1.32796835, -0.43987394, -0.47111407,  0.7539979 ,
        -2.50418114, -0.18685796, -0.70072609, -1.3127504 ],
       [-0.00451976,  1.25606214, -0.33806797, -0.02246793, -0.18475486,
         0.561691  , -1.67242629,  0.34900594,  0.89682632]])